# Generated by Django 5.1.4 on 2025-01-20 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория для аренды',
                'verbose_name_plural': 'Категории для аренды',
                'db_table': 'rent_category',
            },
        ),
        migrations.CreateModel(
            name='RentItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rent_items_images', verbose_name='Изображение')),
                ('price_per_day', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена за день аренды')),
                ('deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Залоговая сумма')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен для аренды')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentitems.rentcategories', verbose_name='Категория')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец продукта')),
            ],
            options={
                'verbose_name': 'Продукт в аренду',
                'verbose_name_plural': 'Продукты в аренду',
                'db_table': 'rent_item',
                'ordering': ('-created_at',),
            },
        ),
    ]
