# Generated by Django 5.1.4 on 2025-01-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='orders',
            new_name='order',
        ),
    ]
